project:
  type: website
  resources:
  - "pdf/*.pdf"
  - "fonts/**"
  
website:
  title: "    "
  bread-crumbs: false
  site-url: https://mroberts1.github.io/fpu-understanding-film-fa25/
  # twitter-card:
  #   creator: "@mroberts_vma"
  #   card-style: summary_large_image
  # favicon: "/img/cropped-cropped-flourish-1-270x270.gif"
  sidebar:
    search: false
    style: "floating"
  navbar:
    background: "#960000"
    search: false
  #   right:
  #     - icon: envelope
  #       aria-label: envelope
  #       href: mailto:martin_roberts@emerson.edu
  #     - icon: mastodon
  #       aria-label: mastodon
  #       href: https://merveilles.town/@dokoissho
  #     - icon: github
  #       aria-label: github
  #       href: https://github.com/mroberts1
  #     - icon: facebook
  #       aria-label: facebook
  #       href: https://facebook.com/mr05301
  #     - icon: twitter
  #       aria-label: twitter
  #       href: https://twitter.com/mroberts_VMA
format:
  html:
    toc: false
    toc-depth: 3
    toc-location: right
    toc-title: '   '
    theme:
      light: ember.scss
      dark: [slate, ember.scss]
    css:
      - custom.scss
    grid:
        sidebar-width: 300px
        body-width: 800px
        margin-width: 300px
        gutter-width: 1em
    fontsize: 1em
    linestretch: 1.5
    smooth-scroll: true
    linkcolor: "#960000"
    title-block-banner: false
  PrettyPDF-pdf: default
fig-responsive: true
image-alt: " "
execute:
  freeze: auto
# reference-location: margin
# citation-location: margin
# editor: visual
