### Overview

This course examines film as a cultural text, focusing on aspects such as genre, movement, and style, and elements such as scriptwriting, story structure, character development, cinematography, editing, and sound. Students will examine how each of these elements contributes to influencing the viewing experience. Films screened are primarily classic American films, but current Hollywood, experimental, or international films may also be included. Addresses GLE Learning Outcomes Arts and Design (AD), Oral Communication (OC), and Applied Learning (AL). Prerequisite: GLE110.

### Reading Assignments

Ed Sikov, _Film Studies: An Introduction_. Second edition. New York: Columbia University Press, 2020. Please order this book either as a print copy or an ebook as soon as possible.

Karen Gocsik, Dave Monahan, and Richard Barsam,  _Writing About Movies_. Fifth edition. New York: W.W. Norton and Company, Inc., 2019.

Other readings will be available as PDFs via links in the syllabus. Please download all PDFs, print them out and mark them up when reading.

## Assignments & Evaluation

Homework exercises (based on Sikov, _Film Studies_) (4, biweekly): 50%  
Midterm (take-home): 15%  
Final (take-home): 15%  
Engagement (including attendance): 20%

## Class Schedule

_Week 1_

08/26 Introduction

08/28 **What Is (a) Film?**

-   [_The Definition of Film_](https://vimeo.com/128097765) (Richard Misek, 2015)

----------

_Week 2_

09/02  **What Is Cinema?**

André Bazin, "[Ontology of the Photographic Image](pdf/bazin-ontology.pdf)"

09/04  **The Cinematic**

-   [Detectives](https://youtu.be/lOz9j3CuNCw)  (Apple, 2022)
-   [_Whodunnit_](https://youtu.be/289zm-hlMWk)  (Apple, 2022)
-   [_Why Do A24 Films Look Like That?_](https://youtu.be/Y4EFuZxEtNI)
-   Matt Zoller Seitz and Chris Wade, “[What Does ‘Cinematic TV’ Really Mean?](https://www.vulture.com/2015/10/cinematic-tv-what-does-it-really-mean.html)” (Vulture, 21 October 2015)

-   Gocsik, Monahan, and Barsam, “The Challenges of Writing About Movies” (_Writing About Movies_, ch. 1)

----------

_Week 3_

09/09 **What is Film Analysis?**

-   Norman N. Holland, [“Seeing Movies Today—Alas](https://www.asharperfocus.com/Seeing-Movies-Now.html)
-   Norman N. Holland, [“Criticism vs. Reviewing”](https://www.asharperfocus.com/criticism.html)

09/11

-   Sikov, “[Mise-en-scène](pdf/sikov-mise-en-scene-1-2.pdf)" (*Film Studies*, chs. 1-2
    
-   Gocsik, Monahan, and Barsam, “Looking at Movies” (_Writing About Movies_, ch. 2)
    

----------

_Week 4_

09/16

NO CLASS (Instructor Absent)

09/18

-   [Kogonada video essays](https://kogonada.com/archive)

**DEADLINE: Homework: Mise-en-scène analysis**

----------

_Week 5_

09/23  **Editing**

-   Sikov, “[Montage](pdf/sikov-montage.pdf))" (*Film Studies*, ch. 4)

09/25 **Kino-eye**

-   [Kino-eye readings](pdf/kino-eye.pdf)
    
-   Watch: _The History of Cutting_, 15 mins.
    
-   [_Man With A Movie Camera_](https://franklinpierce.on.worldcat.org/oclc/52408086) (Dziga Vertov, 1929) [on DVD at the library]
    
-   Gocsik, Monahan, and Barsam, “Formal Analysis” (_Writing About Movies_, ch. 3
    

-   Gocsik, Monahan, and Barsam, “Cultural Analysis” (_Writing About Movies_, ch. 4)

----------

_Week 6_

09/30  **Cinematography**

-   Sikov, _Film Studies_, ch. 3 (“Cinematography”)
-   Daisuke Miyao, “[Cats Love Dark Places: Lighting in](pdf/daisuke-miyao-cinema-cat-people.pdf")

10/02

-   Gocsik, Monahan, and Barsam, “Generating Ideas” (_Writing About Movies_, ch. 5)
    

----------

_Week 7_

10/07 **Hollywood**

-   Dixon and Foster, “[The Hollywood Studio System in the 1930s and 1940s](pdf/dixon-foster-ch4.pdf)" (*A Short History of Film*, chapter 4)
-   Farran Smith Nehme, “[George Cukor’s Way With Women](https://www.criterion.com/current/posts/6331-george-cukor-s-way-with-women)” (Criterion, 2 May 2019)

In-class: What _Price Hollywood?_ (George Cukor, 1932) [excerpt]

10/09

Quiz: Hollywood

-   Gocsik, Monahan, and Barsam, “Researching Movies” (_Writing About Movies_, ch. 6)
    

----------

_Week 8_

10/14 NO CLASS (Fall Break)

10/16

**Narrative**

-   Sikov,  _Film Studies_, ch. 6 (“Narrative: From Scene to Scene”)
-   “[Fabula and Syuzhet](https://en.wikipedia.org/wiki/Fabula*and*syuzhet)” (_Wikipedia_)

----------

_Week 9_

10/21  **Genre**

-   Sikov, _Film Studies_, ch. 10 (“Genre”)
-   Rick Altman, “[A Semantic/Syntactic Approach to Film Genre](pdf/altman-semantic-syntactic.pdf)"

**DEADLINE: Midterm: Hollywood Film Analysis**

10/23

-   Ginette Vincendeau, “[How The French Birthed Film Noir](https://www2.bfi.org.uk/news-opinion/sight-sound-magazine/features/deep-focus/french-film-noir)”

Gocsik, Monahan, and Barsam, “Developing Your Thesis” (_Writing About Movies_, ch. 7)

----------

_Week 10_

10/28 **Soundtracks**

-   Sikov, “Sound” (Film Studies, ch. 5)

10/30

[Mark Korven](https://markkorven.com/) YouTube videos  
[Mark Korven Vimeo](https://vimeo.com/user3424223)

Watch: _The Witch_ (Robert Eggers, 2015)

-   Gocsik, Monahan, and Barsam, “Attending to Style” (_Writing About Movies_, ch. 8)

----------

_Week 11_

11/04 **Color**

-   Richard Misek, “[Film Color](pdf/misek-film-color.pdf)” (in _Chromatic Cinema: A History of Screen Color_ (Chichester: Wiley-Blackwell, 2010), ch. 1)
    
-   Maria Helena Braga e Vaz da Costa, “[Color in Films: A Critical Overview](pdf/color-in-films.pdf)"
    
In-class:  [Color _Motifs in *Black Narcissus*](https://www.criterionchannel.com/color-motifs-in-black-narcissus)  (Kristin Thompson, 2018)

11/06

**DEADLINE: Homework: Genre Analysis**

----------

_Week 12_

11/11  **Auteurism and the New Wave**

-   Sikov, _Film Studies_, ch. 8 (“Filmmakers”)
-   Alexandre Astruc, “[The Birth of a New Avant-Garde: La Caméra-Stylo](http://www.newwavefilm.com/about/camera-stylo-astruc.shtml)”
- François Truffaut, “[A Certain Tendency of French Cinema](http://www.newwavefilm.com/about/a-certain-tendency-of-french-cinema-truffaut.shtml)”
-   [French New Wave](https://cinemawavesblog.com/movements/french-new-wave/) (CinemaWaves website)
-   Samuel Harries, [Movements in Film: French New Wave](https://www.movementsinfilm.com/french-new-wave)
-   [French New Wave: Where to Start](http://www.newwavefilm.com/new-wave-cinema-guide/nouvelle-vague-where-to-start.shtml)

Recommended films:

-   _The 400 Blows_ (François Truffaut, 1959)
-   _Breathless_ (Jean-Luc Godard, 1960)
-   _Cleo from 5 to 7_ (Agnes Varda, 1961)

11/13

- Jonathan Romney, "[Del Toro's *Frankenstein*](frankenstein.qmd)" (*Sight & Sound*, November 2025)

-   Gocsik, Monahan, and Barsam, “Revising Your Work (_Writing About Movies_), ch. 10)

    

----------

_Week 13_

11/18 **Digital Cinema**

Sikov, _Film Studies_, ch. 13 (“Film Studies in the Era of Digital Cinema”)

11/20

-   Graham Edwards, “[Explosive Cocktail](https://franklinpierce.instructure.com/courses/19450/files/2982722?wrap=1 "explosive-cocktail.pdf")” (_Cinefex_ 145 (February 2016): 12-39 - Prince, _Digital Cinema_ (selected chs.)

**DEADLINE: Homework: Auteur Analysis**

----------

_Week 14_

11/25

11/27 NO CLASS (Thanksgiving)

----------

_Week 15_

12/02

12/04 Conclusion

----------

12/05 Classes End

12/06-07 Reading Days

12/08-11 Final Exam Period

**DEADLINE: Final Exam (take-home)**

----------

## Policies & Procedures

### How to do well in this class
Attend all scheduled classes.

Be on time. Don’t leave early.

Complete all reading assignments  **before**  the scheduled class.

Watch all assigned films.

Take notes. The Cornell note-taking system is recommended. If you don’t take notes during class, you will forget 90% of what was discussed there.

Use a free note-taking app like [Obsidian](https://obsidian.md/) and learn how to write in Markdown format.

Ask questions. These should be academic (i.e. related to course topics and materials) rather than administrative (due dates, rubrics etc.).

Administrative questions should be asked outside class, either in person after class or via Canvas Inbox.

### Attendance

Attendance of all scheduled classes is mandatory. Attendance is taken at the beginning of class; if you arrive late, you may miss rolecall, in which case remember to ask to be recorded as Late after class.

### Punctuality

Class begins at 10:50 a.m. and ends at 12:05 p.m. Be sure to arrive in time for the beginning of class. Class does not end until students are dismissed: please do not leave early. Arrival after 11 a.m. will be recorded as Late (L), and three Late count as one Absence. If you need to leave early, please notify me of this before class as a courtesy.

### Absences

You are permitted up to two (2) Excused absences, and a maximum of four (4) absences for any reason.

If you reach 4 absences, you are required to arrange a meeting with me to discuss your status in the course.

### Excused/Unexcused Absence

Absences are recorded as Excused (E) in case of health, emergency, bereavement, professional development (e.g. job interview), or participation in a University sports team. For more than two (2) absences in case of health issues, a doctor’s note is required. All other absences are recorded as Unexcused (U).

### Sports Teams

If you are unable to attend a class due to attending sports events, you are required to email me a list of dates when you expect to be absent. After the missed class, you are required to schedule a meeting with me during my office hour (Thursday 9:30-10:30) to discuss what was missed during your absence.

### Communication

Please use Canvas Inbox for all course-related questions. Other questions can be sent via email ([robertsm@franklinpierce.edu](mailto:robertsm@franklinpierce.edu)). I try to reply to direct messages within 24 hours (except on weekends), and will expect you to do the same.

### Notifications

It is strongly recommended to disable notifications on Canvas.

## Classroom Protocol

### Food and Drink

You may bring a drink to class, but please do not eat when class is in progress.

### Sleeping in class

You are expected to remain alert and attentive at all times during class. If you fall asleep during class, you will receive an informal verbal warning. If the problem recurs, you will receive a second written warning. If the problem continues after this, it will significantly affect your Engagement grade for the course (20%).

### Cellphones

The use of cellphones during class is strictly forbidden.

### Headphones

The use of headphones or earbuds during class is strictly forbidden

### Laptop Privileges

The use of laptops or tablets (e.g. iPads) is permitted during class for taking notes ONLY. Any other use is unauthorized, and if detected will result in the withdrawal of your laptop privileges for the remainder of the semester. This means that you will be required to take notes by hand with pen and paper from that point on.

### Timeouts

Since this is a short class (1.25 hrs), you are expected to remain present in class throughout except in case of emergency. Please do not keep walking in and out of class. This applies particularly when screenings are in progress.

### Hoods

Hoods must be worn **down** at all times. This is so that I can see at all times that you are not using headphones (see above). Room temperature does not require wearing of hats or other headgear.

### Warnings and Engagement Grade

Non-compliance with the above policies will result in an initial verbal warning.

If the non-compliance continues, I will request a meeting with you to discuss the issue, and it will impact your Engagement grade (20%).